# Generated by Django 3.2.5 on 2022-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=60)),
                ('Address', models.CharField(default='', max_length=60)),
                ('city', models.CharField(default='', max_length=60)),
                ('state', models.CharField(default='', max_length=60)),
                ('zip', models.CharField(default='', max_length=60)),
                ('query', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
